[package]
name = "staff-search"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
sdl2 = {version = "0.38.0", features = ["image","ttf"]}
reqwest = { version = "0.12.23", features = ["blocking", "default-tls","gzip", "brotli"] }
dialog = "0.3.0"
image = "0.25.8"

